GET http://localhost:3000/

###
GET http://localhost:3000/orders

###
POST http://localhost:3000/orders
Content-Type: application/json

{
    "asset_id": "1111",
    "price": 50
    //"status": "TESTE"
}

###
GET http://localhost:3000/assets

###
POST http://localhost:3000/assets
Content-Type: application/json

{
    "id": "1112",
    "symbol": "USIM5"
}